PostToolUse:
  - matcher: "Write|Edit|MultiEdit"
    conditions:
      - type: file_extension
        value: ".go"
    actions:
      - type: command
        command: "gofmt -w {tool_input.file_path}"

PreToolUse:
  - matcher: "Bash"
    conditions:
      - type: command_contains
        value: "git add"
    actions:
      - type: output
        message: "⚠️  Bashコマンドでgit addを実行しようとしています。semantic commitワークフローを使用することを検討してください。"