PreToolUse:
  - matcher: "Bash"
    conditions:
      - type: command_starts_with
        value: "git add"
    actions:
      - type: output
        message: "git addは直接使わず、カスタムスラッシュコマンドを使いましょう"
        # exit_statusを明示的に指定しない場合、outputアクションのデフォルトの2が使われる

  - matcher: "Bash"
    conditions:
      - type: command_starts_with
        value: "python"
    actions:
      - type: output
        message: "pythonは使わず`uv`を代わりに使いましょう"
        exit_status: 2  # 明示的に2を指定

  - matcher: "Bash"
    conditions:
      - type: command_starts_with
        value: "echo"
    actions:
      - type: output
        message: "この警告は正常に出力されます（ExitStatus 0）"
        exit_status: 0  # 明示的に0を指定してstdoutに出力